# Generated by Django 4.2.7 on 2024-01-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_tabla', models.TextField(help_text='Ingrese la descripción tipo tabla')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='fichas_tecnicas/')),
                ('datos_texto_varios', models.TextField(blank=True, help_text='Ingrese datos de texto varios en formato de lista separada por comas', null=True)),
            ],
        ),
    ]
